### ISSUE TITLE
Error: Cannot promisify an API that has normal methods with 'Async'-suffix

### ISSUE THREAD

**Issue by lyndenzhang** [trek10inc/lambda-error-hound#1]
$ lambda-error-hound error -f MyLambdaFunction
/usr/lib/node_modules/lambda-error-hound/node_modules/bluebird/js/release/promisify.js:54
                    throw new TypeError("Cannot promisify an API that has normal methods with '%s'-suffix\u000a\u000a    See http://goo.gl/MqrFmX\u000a"
                    ^

TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix

    See http://goo.gl/MqrFmX

    at checkValid (/usr/lib/node_modules/lambda-error-hound/node_modules/bluebird/js/release/promisify.js:54:27)
    at promisifiableMethods (/usr/lib/node_modules/lambda-error-hound/node_modules/bluebird/js/release/promisify.js:77:5)
    at promisifyAll (/usr/lib/node_modules/lambda-error-hound/node_modules/bluebird/js/release/promisify.js:241:9)
    at Function.Promise.promisifyAll (/usr/lib/node_modules/lambda-error-hound/node_modules/bluebird/js/release/promisify.js:311:12)
    at Object.<anonymous> (/usr/lib/node_modules/lambda-error-hound/index.js:10:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by lyndenzhang** [comment]
node --version
v8.11.4

**Comment by Duncan00** [comment]
same here

**Comment by tszpinda** [comment]
you can get around the error, by cloning the repo and running:
```
npm install
node index.js error -f "<short_lambda_name>"
```

as the error is caused by upgraded aws lib

**Comment by trondhindenes** [comment]
Wouldn't it be better if the proper aws package version was specified?

**Comment by abisee** [comment]
I'm still having this problem. `node --version` is `v12.13.1`. I tried doing @tszpinda's suggestion but I still get the same error. Does anyone have any ideas?

**Comment by ronkorving** [comment]
This package looked so promising... sigh :-/
